"""update goal class

Revision ID: 81914615b8d5
Revises: 459ebeb45905
Create Date: 2023-05-08 17:00:43.367687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81914615b8d5'
down_revision = '459ebeb45905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
